# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
ignore = [
    # Accepted low-severity warnings from sled dependencies
    "RUSTSEC-2025-0057",  # fxhash unmaintained (via sled, no alternatives)
    "RUSTSEC-2024-0384",  # instant unmaintained (via sled, no known vulnerabilities)
]

[licenses]
# Ensure only acceptable licenses
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
