name: Publish to MCP Registry

on:
  push:
    tags: ["mcp-v*"]  # Triggers on MCP version tags like mcp-v0.1.2
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --all --release

      - name: Build release
        run: cargo build --release --package pforge-cli

      - name: Publish to crates.io
        if: startsWith(github.ref, 'refs/tags/mcp-v')
        run: |
          cargo publish --package pforge-config --token ${{ secrets.CARGO_TOKEN }} || true
          sleep 10
          cargo publish --package pforge-macro --token ${{ secrets.CARGO_TOKEN }} || true
          sleep 10
          cargo publish --package pforge-runtime --token ${{ secrets.CARGO_TOKEN }} || true
          sleep 10
          cargo publish --package pforge-codegen --token ${{ secrets.CARGO_TOKEN }} || true
          sleep 10
          cargo publish --package pforge-cli --token ${{ secrets.CARGO_TOKEN }} || true
        continue-on-error: true

      - name: Install MCP Publisher
        run: |
          PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
          curl -sL "https://github.com/modelcontextprotocol/registry/releases/download/v1.2.3/mcp-publisher_1.2.3_${PLATFORM}_${ARCH}.tar.gz" | tar xz
          chmod +x mcp-publisher

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish
